report_section_order:
  software_versions:
    order: -1000
  "pipelines-technology-nanopore_demux-summary":
    order: -1001

export_plots: true

# Run only these modules
run_modules:
  - custom_content
  - fastqc
  - pycoqc
  - nanostat

module_order:
  - fastqc
  - pycoqc
  - nanostat
  - custom_content
