# report_section_order:
#   software_versions:
#     order: -1000
#   "cas9point4-summary":
#     order: -1001

export_plots: true

# Run only these modules
run_modules:
  - custom_content
  - fastqc
  - pycoqc

module_order:
  - fastqc
  - pycoqc